[zabbix-server]
MainZabbix ansible_host=192.168.122.185 ansible_user=admin ansible_ssh_private_key_file=./adminkey ansible_become=true ansible_ssh_common_args='-o IdentitiesOnly=yes'
[zabbix-agent]
Worker1 ansible_host=192.168.122.219 ansible_user=admin ansible_ssh_private_key_file=./adminkey ansible_become=true ansible_ssh_common_args='-o IdentitiesOnly=yes'
Worker2 ansible_host=192.168.122.246 ansible_user=admin ansible_ssh_private_key_file=./adminkey ansible_become=true ansible_ssh_common_args='-o IdentitiesOnly=yes'