---
- name: Check .env
  ansible.builtin.fail:
    msg: "ERORR: File .env does not exist!"
  when: not ('.env') is file
  run_once: true
  delegate_to: localhost

- name: Install zabbix
  ansible.builtin.import_tasks: install_zabbix_server.yml
  tags:
    - install

- name: Configure панели zabbix
  ansible.builtin.import_tasks: conf_server.yml
  tags:
   - setup